Book/pyDjango/ch99/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name='blog'
urlpatterns=[

    # Example:/blog/
    path('', views.PostLV.as_view(), name='index'),

    
    # Example:/blog/post/ (same as /blog/)
    path('post/', views.PostLV.as_view(), name='post_list'),

    
    # Example:/blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    
    # Example:/blog/archive/
    path('archive', views.PostAV.as_view(), name='post_archive'),

    
    # Example:/blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),


    # Example:/blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),


    # Example:/blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    

    # Example:/blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    
]

Book/pyDjango/ch99/bookmark/urls.py
from django.urls import path
from bookmark.views import BookmarkLV, BookmarkDV

app_name='bookmark'
urlpatterns=[
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>', BookmarkDV.as_view(), name='detail'),
]

Book/pyDjango/ch99/mysite/urls.py
# 1번

from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
]

Book/pyDjango/ch99/blog/models.py
from django.db import models
from django.urls import reverse

class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique = True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_dt=models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table='blog_posts'
        ordering = ('-modify_dt',)

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug))
    def get_previous(self):
        return self.get_previous_by_modify_dt()
    def get_next(self):
        return self.get_next_by_modify_dt()

Book/pyDjango/ch99/bookmark/models.py
from django.db import models

# Create your models here.

class Bookmark(models.Model):
    title=models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)

    def __str__(self):
        return '%s %s' %(self.title, self.url)

Book/pyDjango/ch99/blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView


from blog.models import Post

#--- ListView
class PostLV(ListView):
    model=Post
    template_name = 'blog/post_all.html'
    context_object_name ='posts'
    paginate_by =2



#--- DetailView
class PostDV(DetailView):
    model=Post



#--- ArchiveView
class PostAV(ArchiveIndexView):
    model=Post
    date_field = 'modify_dt'


class PostYAV(YearArchiveView):
    model=Post
    date_field = 'modify_dt'
    make_object_list = True


class PostMAV(MonthArchiveView):
    model=Post
    date_field = 'modify_dt'


class PostDAV(DayArchiveView):
    model=Post
    date_field = 'modify_dt'


class PostTAV(TodayArchiveView):
    model=Post
    date_field = 'modify_dt'

Book/pyDjango/ch99/bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark

class BookmarkLV(ListView):
    model = Bookmark
    
class BookmarkDV(DetailView):
    model = Bookmark

Book/pyDjango/ch99/mysite/views.py
from django.views.generic import TemplateView

#--- TemplateView
class HomeView(TemplateView):
    template_name = 'home.html'

Book/pyDjango/ch99/blog/templates/blog/post_all.html
<h1>Blog List</h1>

<br>
{% for post in posts %}
    <h3><a href="{{ post.get_absolute_url }}">{{post.title}}</a></h3>
    {{post.modify_dt | date:"N d Y"}}
    <p>{{post.description}}</p>
{% endfor %}

<br>
<div>
    <span>
        {% if page_obj.has_previoust %}
        <a href="?page{{ page_obj.previoust_page_number }}">PreviousPage</a>
        {% endif %}

        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            
            <a href="?page{{ page_obj.next_page_number }}">NextPage</a>
        {% endif %}
    </span>
</div>

Book/pyDjango/ch99/blog/templates/blog/post_archive.html
<h1>Post Archives until {% now "N d, Y" %}</h1>
<ul>
    {% for date in date_list %}
    <li style="display: inline;">
    <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year {{ date|date:"Y" }}</a></li>
    {% endfor %}
</ul>
<br/>
<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_abosolute_url }}"><strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>

Book/pyDjango/ch99/blog/templates/blog/post_archive_day.html
<h1>Post Archives for {{ day|date:"N d, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_abosolute_url }}"><strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>

Book/pyDjango/ch99/blog/templates/blog/post_archive_month.html
<h1>Post Archives for {{ month|date:"N, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_abosolute_url }}"><strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>

Book/pyDjango/ch99/blog/templates/blog/post_archive_year.html
<h1>Post Archives for {{ year|date:"Y" }}</h1>

<ul>
    {% for date in date_list %}
    <li style="display: inline;">
    <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:"F" }}</a></li>
    {% endfor %}
</ul>
<br>
<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_abosolute_url }}"><strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>

Book/pyDjango/ch99/blog/templates/blog/post_detail.html
<h2>{{object.title}}</h2>

<p>
    
    {% if object.get_previous %}
    <a href="{{ object.get_previous.get_absolute_url }}" title="View previous post">
        &laquo;- {{object.get_previous}}
    </a>
    {% endif %}

    
    {% if object.get_next %}
    | <a href="{{ object.get_next.get_absolute_url }}" title="View next post">
        {{object.get_next}} -&laquo; 
    </a>
    {% endif %}

</p>
<p>{{ object.modify_dt|date:"j F Y" }}</p>
<br>

<div>
    {{ object.content|linebreaks }}
</div>
</div>

Book/pyDjango/ch99/bookmark/templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html>
<head>
    
    <title>Django Bookmark List</title>
</head>
<body>
    <div id="content">
        <h1>{{object.title}}</h1>

        <ul>
            <li>URL: <a href="{{object.url}}">{{object.url}}</a></li>

        </ul>
    </div>
</body>
</html>

Book/pyDjango/ch99/bookmark/templates/bookmark/bookmark_list.html
<!DOCTYPE html>
<html>
<head>
    
    <title>Django Bookmark List</title>
</head>
<body>
    <div id="content">
        <h1>Bookmark List</h1>

        <ul>
            {% for bookmark in object_list %}
            <li><a href="{% url 'detail' bookmark.id %}">{{bookmark.title}}</a></li>
            {%endfor%}

        </ul>
    </div>
</body>
</html>

Book/pyDjango/ch99/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Django Web Programming {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    {% block extra-style %}{% endblock %}
</head>

<body style="padding-top: 90px;">

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
        <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Django - Python Web Programming</span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item mx-1 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'bookmark:index' %}">Bookmark</a>
                </li>
                <li class="nav-item btn btn-primary">
                    <a class="nav-link dropdown-toggle" href="{% url 'blog:index' %}">Blog</a>
                </li>
                <li class="nav-item mx-1 btn btn-primary">
                    <a class="nav-link text-white" href="">Photo</a>
                </li>


                <li class="nav-item dropdown mx-1 btn btn-primary">
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Until</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a>
                        <a class="dropdown-item" href="">Search</a>
                    </div>
                </li>

            </ul>
            <form class="form-inline my-2" action="" method="post">{% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="global Search" name="search_word">
            </form>
        </div>
    </nav>

    <div class="container">

    {% block content %}{% endblock %}
    </div>
    {% block footer %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
    {% block extra-script%}{% endblock %}

</body>

</html>

Book/pyDjango/ch99/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}home.html {% endblock %}

{{% block extra-style %}
<style type="text/css">
    .hom-image{
        background-image: url("{% static 'img/lion.jog' %}");
        background-repeat: no-repeat;
        background-position: center;
        background-size: 100%;
        height: 500px;
        border-top: 10px solid #ccc;
        border-bottom: 10px solid #ccc;
        padding: 20px 0 0 20px;
    }
    .title{
        color: #c80;
        font-weight: bold;
    }
    .powered{
        position: relative;
        top: 77%;
        color: #cc0;
        font-style: italic;
    }
</style>
{% endblock %}
{% block content %}
<div class="home-image">
    <h2 class="title">Django - Python Web Programming</h2>
    <h4 class="powered"><i class="fas fa-arrow-circle-right"></i> powered by django and bootstrap</h4>
</div>

<hr style="margin: 10px 0;">
<div class="row text-center">
    <div class="col-sm-6">
        <h3>Bookmark App</h3>
        <p>Bookmark is a Uniform Resource Identifier (URI) that is stored for later retrieval in any of various storage formats.
            You can store your own bookmarks by Bookmark application.
            It's also possible to update or delete your bookmarks.
        </p>
    </div>
    <div class="col-sm-6">
        <h3>Blog App</h3>
        <p>This application makes it possible to log daily events or write your own interests such as hobbies, techniques, etc.
            A typical blog combines text, digital images, and links to other blogs, web pages, and other media related to its topic.
        </p>
    </div>
</div>
    {% endblock content %}
    {% block footer %}
    <footer class="fixed-bottom bg-info">
        <div class="text-white font-italic text-right mr-5">Copyright &copy; 2019 DjangoBook by shkim</div>
    </footer>
{% endblock %}